apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-pingpong
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: secret-pingpong
    spec:
      containers:
      - name: pingpong
        image: gospotcheck/go-docker-example
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: port
              key: PORT
