apiVersion: v1
kind: Service
metadata:
  name: secret-pingpong-service
  labels:
    run: secret-pingpong-service
spec:
  type: NodePort
  ports:
  - port: 7000
    protocol: TCP
  selector:
    app: secret-pingpong
    